Draft: fix found issues of comm replay
facebookresearch/param pull request #180
Opened 2024-09-16 17:30 UTC by TaekyungHeo

**This MR is just for diff, please don't merge.**

# Depend On
1. [[c10d] fix sequence numbers for coalesced operations #135132](https://github.com/pytorch/pytorch/pull/135132)
2. [fix sequence number for group #134578](https://github.com/pytorch/pytorch/pull/134578)

# Summary
1. fix replay to send/recv
2. fix blocking option
3. fix process group update of barrier
4. Comment out unused function incast and multicast
5. remove function extractCommsInfo() for deprecatd basic trace
6. fix wait comm op for both collective and p2p

# TestPlan
comm_replay --trace-type et --trace-path /home/sanshang/lustre_storage/000_code/chakra/comm_replay_eval_06/training/et_iter_50_51 --num-replays 10
![image](https://github.com/user-attachments/assets/a6d70cac-3c57-4cb8-9b36-cb5ba2fdd639)

2024-10-10 20:24 UTC, shengfukevin requested changes
HI Sanshan,

Thanks for implementing this P2P feature. Overall looks good. Please check my inline comments. 

Also please provide a couple ET for P2P cases. We will put them into our integration tests. 

Regards
Sheng

2024-10-11 12:39 UTC, GSSBMW commented on et_replay/comm/backend/base_backend.py
> -            "incast": self.incast,  # pyre-ignore[16]:
Done

2024-10-11 12:39 UTC, GSSBMW commented on et_replay/comm/commsTraceParser.py
> +    is_seq = lambda x: isinstance(x, list) and len(x) == 2 and isinstance(x[0], int) and isinstance(x[1], bool)
Done.

2024-10-11 12:40 UTC, GSSBMW commented on et_replay/comm/commsTraceParser.py
> +        # ["wait", "barrier", "init"] record 1st element as seq, whose 1st element is sequence number as int, 2nd element is isP2P as bool
Done

2024-10-11 12:40 UTC, GSSBMW commented on et_replay/comm/comms_utils.py
> -            "--z",
Done

2024-10-11 12:40 UTC, GSSBMW commented on et_replay/comm/backend/pytorch_dist_backend.py
> +    '''
Done

2024-10-11 12:40 UTC, GSSBMW commented on et_replay/comm/backend/pytorch_dist_backend.py
> +    '''
Done for removing.

2024-10-11 12:43 UTC, GSSBMW commented
@shengfukevin 
Has tried to resolve all your comments. Please help review, thanks!
For ET of P2P, does pytorch test has such cases to generate? Otherwise I need to write test to generate such traces.

2024-10-14 03:36 UTC, shengfukevin approved these changes

2024-10-15 16:45 UTC, c-p-i-o commented
@TaekyungHeo, do you want to address the linter errors?
You can run:
`make lint` followed by `lintrunner -a` that should hopefully take care of the linter errors for you.

2024-10-21 21:19 UTC, shengfukevin commented
the duplicated PR has been merged aleady.

2024-10-21 21:19 UTC, closed without merging